@startuml sequence
title Diagramme de séquence : Changer le mot de passe
skinparam sequenceMessageAlign center
User -> Front : change de mot de passe
Front -> Back : envoie la requête du changement
Back -> BDD : change le mot de passe dans la BDD
BDD -> Back : Confirmation du changement
Back -> Front : Renvoie un message de confirmation
Front -> User : Affiche le message de confirmation

@enduml