@startuml notes
title Notations des professeurs  
|Prof|
'on indique le point de demarrage du diagramme
start
:Clic sur l intranet;
|Serveur|
' on donne une condition pour le diagramme
if (Verifie  si user est connecté en tant que prof) is (non) then (oui)
else
|Prof|
    #red: **Message d erreur**;
stop
endif
|Prof|
:panel des professeurs;
:onglets des éléves;
:choisie un éléve;
:ajouter une note;
repeat
:remplie le formulaire;
|Serveur|
:verifie les infos;
'on indique une condition qui peut se repeter
repeat while (Les infos sont correct?) is (non) not (oui)
|Prof|
:valider;
end
@enduml