@startuml notes
title Notations des professeurs  
|Prof|
start
:Clic sur l intranet;
|Serveur|
if (Verifie  si user est connecté en tant que prof) is (non) then (oui)
else
:Message d erreur;
stop
endif
|Prof|
:panel des professeurs;
:onglets des éléves;
:choisie un éléve;
:ajouter une note;
repeat
:remplie le formulaire;
|Serveur|
:verifie les infos;
repeat while (Les infos sont correct?) is (non) not (oui)
|Prof|
:valider;
end
@enduml