@startuml
left to right direction
actor Eleve

rectangle "Système de l'École" {
  usecase "Voir la Page d'Accueil" as VoirAccueil
  usecase "Voir les Vacances" as VoirVacances
  usecase "Voir les Concours" as VoirConcours
  usecase "Voir les Bourses" as VoirBourses

  usecase "Accéder à son Compte" as AccederCompte
  usecase "Voir son Profil (via Compte)" as VoirProfilCompte
  usecase "Inscription" as Inscription
  usecase "Connexion" as Connexion

  usecase "Gérer son Profil" as GererProfil
  usecase "Modifier Profil" as ModifierProfil
  usecase "Modifier Mot de Passe" as ModifierMDP
  usecase "Modifier Image" as ModifierImage

  usecase "Aller sur Intranet" as AllerIntranet
  usecase "Consulter sa Fiche" as ConsulterFiche
  usecase "Voir Photo" as VoirPhoto
  usecase "Voir Notes" as VoirNotes
  usecase "Voir Commentaires" as VoirCommentaires

  usecase "Aller sur Cours" as AllerCours
  usecase "Voir Liste des Matières" as VoirListeMatieres
  usecase "Voir Détails Matière" as VoirDetailsMatiere
  usecase "Voir Professeur Matière" as VoirProfMatiere

  usecase "Aller sur Boutique" as AllerBoutique
  usecase "Voir Liste des Articles" as VoirListeArticles
  usecase "Télécharger Formulaire Commande" as TelechargerFormulaireCommande
  usecase "Télécharger Formulaire Paiement" as TelechargerFormulairePaiement

  usecase "Aller à la Liste des Profs" as AllerListeProfs
  usecase "Voir Liste des Professeurs" as VoirListeProfs
  usecase "Voir Détails du Professeur" as VoirDetailsProf

  usecase "Aller à la Liste des Maisons" as AllerListeMaisons
  usecase "Voir Liste des Maisons" as VoirListeMaisons
}

Eleve -- VoirAccueil
VoirAccueil -- VoirVacances : includes
VoirAccueil -- VoirConcours : includes
VoirAccueil -- VoirBourses : includes

Eleve -- AccederCompte
AccederCompte -- VoirProfilCompte
AccederCompte -- Inscription
AccederCompte -- Connexion

Eleve -- GererProfil
GererProfil -- ModifierProfil
GererProfil -- ModifierMDP
GererProfil -- ModifierImage

Eleve -- AllerIntranet
AllerIntranet -- ConsulterFiche
ConsulterFiche -- VoirPhoto : includes
ConsulterFiche -- VoirNotes : includes
ConsulterFiche -- VoirCommentaires : includes

Eleve -- AllerCours
AllerCours -- VoirListeMatieres
VoirListeMatieres -- VoirDetailsMatiere : extends
VoirDetailsMatiere -- VoirProfMatiere : includes

Eleve -- AllerBoutique
AllerBoutique -- VoirListeArticles
AllerBoutique -- TelechargerFormulaireCommande
AllerBoutique -- TelechargerFormulairePaiement

Eleve -- AllerListeProfs
AllerListeProfs -- VoirListeProfs
VoirListeProfs -- VoirDetailsProf : extends

Eleve -- AllerListeMaisons
AllerListeMaisons -- VoirListeMaisons

@enduml