@startuml

left to right direction

: user : as U
package Ecole {
    : Eleve : as E
: Admin : as A
: Prof : as P
}

package Site {
    usecase "Acceuil" as UC1
    usecase "inscription" as UCI
    usecase "connexion" as UCC
    usecase "Compte" as UC2
    usecase "Cours" as UC3
    usecase "Intranet" as UC4
    usecase "liste Prof" as UC5
    usecase "Boutique" as UC6
    usecase "Maison" as UC7
    
    usecase "modifier compte" as UC8
    usecase "modifier/add cours" as UC9
    usecase "lire cours selon matiere" as UC10
    usecase "ajouter note/com eleve" as UC11
    usecase "lire note/com eleve" as UC12
    usecase "commander" as UC14
    usecase "payer" as UC15
    
    usecase "ajouter/suppr article" as UC16
    usecase "ajouter/suppr compte" as UC17
    

}

U --> UC1
U --> UCI
U --> UC6
U --> UC3


E --> UC4
E --> UC12
E --> UC5
E --> UC6
E --> UC7


P --> UC11
P --> UC6

A --> UC9
A --> UC11
A --> UC16
A --> UC17

P --> E
A --> P

P -- UCC : include
E -- UCC :!include
UCC -- UC4 :include
UCC -- UC12 : include
UCC -- UC10 : include
UCC -- UC8 : include
UC6 -- UC14 :include
UC6 -- UC15 :include




@enduml
