@startuml Moeusercase

left to right direction


package Ecole {
    actor Eleve  as E #LightBlue;text:LightBlue
    actor Admin  as A #Red;text:Red
    actor Prof  as P #Green;text:Green
}
actor user  as U #Pink;text:Pink

package Site {
    usecase "Acceuil" as UC1 #Pink
    usecase "inscription" as UCI #Pink
    usecase "connexion" as UCC #Pink
    usecase "Cours" as UC3 #Pink
    usecase "Intranet" as UC4 #LightBlue
    usecase "Page Prof" as UC5 #Pink
    usecase "Detail Prof" as UCDP #Pink
    usecase "Boutique" as UC6 #Pink
    usecase "Maison" as UC7 #Pink

    usecase "modifier Information" as UC8 #LightBlue
    usecase "Add Information" as UC8A #LightBlue
    usecase "Supr Information" as UC8S #LightBlue
    usecase "modifier cours" as UC9 #Red;text:White
    usecase "Add cours" as UC9A #Red;text:White
    usecase "Supr cours" as UC9S #Red;text:White
    usecase "Detail Cours" as UC10 #Pink
    usecase "Modifier note/com eleve" as UC11 #Green
    usecase "Add note/com eleve" as UC11A #Green
    usecase "Supr note/com eleve" as UC11S #Green
    usecase "lire note/com eleve" as UC12 #LightBlue
    usecase "Form commande" as UC14 #Pink
    usecase "Form payer" as UC15 #Pink


    usecase "Modifier article" as UC16 #Red;text:White
    usecase "Add article" as UC16A #Red;text:White
    usecase "Supr article" as UC16S #Red;text:White
    usecase "Supr compte" as UC17S #Red;text:White
    usecase "Modifier Prof" as UCMP #Red;text:White
    usecase "Add Prof" as UCMPA #Red;text:White
    usecase "Supr Prof" as UCMPS #Red;text:White
    usecase "Modifier Maison" as UCMM #Red;text:White
    usecase "Add Maison" as UCMMA #Red;text:White
    usecase "Supr Maison" as UCMMS #Red;text:White
    usecase "Modif Form Paiment" as UCMFP #Red;text:White
    usecase "Add Form Paiment" as UCAFP #Red;text:White
    usecase "Supr Form Paiment" as UCSFP #Red;text:White
    usecase "Modif Form Commande" as UCMFC #Red;text:White
    usecase "Add Form Commande" as UCAFC #Red;text:White
    usecase "Supr Form Commande" as UCSFC #Red;text:White

    usecase "Modifier role" as UCRM #Red;text:White
    usecase "Ajouter role" as UCRA #Red;text:White
    usecase "Supr role" as UCRS #Red;text:White



}

U --> UC1
U --> UC3
U --> UC10
U --> UC5
U --> UCDP
U --> UC7
U --> UC6
U --> UC14
U --> UC15
U --> UCI
U --> UCC

E --> UC4
E --> UC8
E --> UC8A
E --> UC8S
E --> UC12

P --> UC11
P --> UC11A
P --> UC11S

A --> UC16
A --> UC16A
A --> UC16S
A --> UC17S
A --> UC9
A --> UC9A
A --> UC9S
A --> UCMP
A --> UCMPA
A --> UCMPS
A --> UCMM
A --> UCMMA
A --> UCMMS
A --> UCMFP
A --> UCAFP
A -->UCSFP
A -->UCMFC
A -->UCAFC
A -->UCSFC
A --> UCRM
A --> UCRA
A --> UCRS

UC8 ..> UCC : include
UC8A ..> UCC : include
UC8S ..> UCC : include 
UC12 ..> UCC : include 
UC4 ..> UCC : include 
UC11A ..> UCC : include 
UC11  ..> UCC : include 
UC11S ..> UCC : include
UC16  ..> UCC : include 
UC16S ..> UCC : include 
UC16A ..> UCC : include 
UC9 ..> UCC : include
UC9A ..> UCC : include 
UC9S ..> UCC : include  
UC17S ..> UCC : include 
UCMP ..> UCC : include 
UCMPS ..> UCC : include 
UCMPA ..> UCC : include 
UCMM ..> UCC : include 
UCMMA ..> UCC : include 
UCMMS ..> UCC : include 
UCMFP ..> UCC : include 
UCAFP ..> UCC : include 
UCSFP ..> UCC : include 
UCMFC ..> UCC : include 
UCAFC ..> UCC : include 
UCSFC ..> UCC : include
UCRM ..> UCC : include 
UCRA ..> UCC : include 
UCRS ..> UCC : include  

E -|> U : herite
P -|> E : herite
A -|> P : herite 

@enduml
