@startuml

left to right direction
actor "Prof" as p
rectangle intanet {
  usecase "consulter le profile" as uc1
  usecase "mettre les notes " as uc2
  usecase "se connecter" as uc3
  usecase "consulter le profile des eleve" as uc4

}
p --> uc1
p-->uc2
p-->uc3

p-->uc4




note right of (uc1)
en tant que prof connecté je veux modifier mon profile
end note

note right of (uc4)
en tant que prof connecté je veux consulter le  profile de mes eleve
end note
note right of (uc2) 
en tant que prof connecter je veux mettre a jour les notes de mes eleves 
end note

@enduml
