@startuml
left to right direction
actor User as u 
package ecole {
    actor Elèves as e 
    actor Professeur as p   
}

package {
    usecase "créer un compte" as UC1
    usecase "se connecter" as UC2
    usecase "voir ces notes" as UC3
    usecase "ajouter des infos perso" as UC4
    usecase "ajouter des notes et observation" as UC5
    usecase "voir ces notes" as UC6
    usecase "compléter son profil" as UC7
    usecase "accéder à la boutique" as UC8
    usecase "passer commande" as UC9
}

u --> UC1
u --> UC8
u --> UC9

e --> UC1
e --> UC2
e --> UC3
e --> UC4
e --> UC6
e --> UC7
e --> UC8
e --> UC9

p --> UC2
p --> UC5
p --> UC8
p --> UC9
@enduml